### ISSUE TITLE
$max undefined property error in logs

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-mod_turnitintooltwo#544] opened 2019-08-13 08:29 UTC
Seeing this in Apache logs
Moodle 3.7.1
TII v2019070201

PHP Notice:  Undefined property: stdClass::$max in /path/to/moodle/mod/turnitintooltwo/lib.php on line 1745

**Comment by aspark21** [comment] 2019-08-13 08:31
Also:
PHP Notice:  Undefined variable: scoreinner in /path/to/moodle/mod/turnitintooltwo/turnitintooltwo_view.class.php on line 1251

**Comment by dwinn** [comment] 2019-08-14 09:18
Hi @aspark21,

Thanks for the report. We will get this looked at.

**Comment by aruethe2** [comment] 2020-01-29 21:13
I believe this was fixed by commit 356f3db5136a7780d55d165a4dddd99aeb93fc44.  The issue is still open, just letting you know that you can probably close it.

**Closed** 2020-01-30 08:00 UTC
