### ISSUE TITLE
Peermark Manager iframe issue.

### ISSUE THREAD

**Issue by mfabriczy** [turnitin/moodle-mod_turnitintooltwo#476] opened 2018-10-11 00:35 UTC
When launching the Peermark Manager, the iframe does not load properly - instead, showing the LTI parameters that were sent.

<img width="750" alt="screen shot 2018-10-11 at 11 02 34 am" src="https://user-images.githubusercontent.com/2814676/46773529-6114f100-cd45-11e8-82b5-109bf8b35101.png">

**Comment by jmcgettrick** [comment] 2021-03-10 11:29
We haven't seen any other reports of this and we can't reproduce so I'm closing.

**Closed by jmcgettrick** 2021-03-10 11:29 UTC
