### ISSUE TITLE
The email notification sent to the users who enrollment has expired

### ISSUE THREAD

**Issue by mileginy** [turnitin/moodle-mod_turnitintooltwo#345] opened 2017-06-23 01:30 UTC
Instructor/tutor reported they still receiving email notification from TURNITIN even though their enrollment in the course has expired. 

Please check and fix.

**Comment by jmcgettrick** [comment] 2018-01-02 11:42
Duplicate of https://github.com/turnitin/moodle-mod_turnitintooltwo/issues/373

**Closed by jmcgettrick** 2018-01-02 11:42 UTC
