### ISSUE TITLE
Sorting issues in submission inbox

### ISSUE THREAD

**Issue by davidmhatton** [turnitin/moodle-mod_turnitintooltwo#365] opened 2017-08-10 08:31 UTC
## Summary
Assignments where only some students have submitted have been known to sort incorrectly (i.e. non-alphabetically) on student first name.

**Comment by MarkRoche1** [comment] 2018-02-19 14:51
Hi David,

We've just upgraded to Turnitin v2017112301 and have encountered this bug. Is it fixed in the latest version? If not, are there any workarounds?

Thanks
Mark

**Comment by cb526** [comment] 2019-09-23 14:07
Just reporting that this bug is still present.

**Comment by sleitao** [comment] 2021-02-11 12:31
Just to confirm that the issue is still present in version 2020072201.
It doesn't sort by student first name.

**Comment by upascal** [comment] 2021-12-13 19:00
I also have this bug. How do we fix it?

**Comment by jack-tii** [comment] 2024-08-07 13:10
This was fixed in our latest release

**Closed by jack-tii** 2024-08-07 13:10 UTC
Labels: bug, known
