### ISSUE TITLE
Turnitin migration tool confused by assignment with reduced number of parts

### ISSUE THREAD

**Issue by james-cnz** [turnitin/moodle-mod_turnitintooltwo#516] opened 2019-03-06 02:01 UTC
Steps to reproduce:

1. Set  Site administration / Plugins / Activity modules / Turnitin Assignment 2 / V1 Migration / Migration action at assignment launch: Prompt instructor at launch.
2. Create a new Turnitin Assignment v1 with more than one part.
3. Edit the assignment settings, and reduce the number of parts.
4. Log out of Moodle and back in, if necessary, so migration prompt shows.
5. Open and migrate assignment.

When you open the new assignment, the original number of parts shows.
Under the assignment settings, however, the original number [EDIT: reduced number] of parts shows.
Under the assignment settings, trying to increase the number of parts generates an error.

**Comment by james-cnz** [comment] 2019-03-06 02:06
I guess some existing migrated assignments will be affected, so it would be good to have a way to locate and fix these.

**Comment by dwinn** [comment] 2019-03-06 11:12
Hi @james-cnz,

Thank you for reporting this bug with the migration tool. I have been able to reproduce it locally.

I have done some investigation and this appears to be due to how we handle the deletion of parts. In V1 we flag the part as deleted in the mdl_turnitintool_parts table. This then gets migrated with the deleted flag still in place. In V2, we don't seem to use this flag because instead of flagging the part as deleted we remove the part from the database. This difference has meant that once migrated the deleted V1 part is now visible in the inbox.

From what I can see, the error when you attempt to increase the number of parts in the migrated assignment is down to the part name clashing with the deleted part name so a workaround would be to give the new part a different name. The part which has been deleted could also be deleted via the assignment settings.

I have made a ticket on our end to fix the bug with the migration tool but I'm not sure we will be able to put in a fix to locate and fix existing data as there are too many risks involved with programmatically deleting data. For example a part which reappeared after a migration may have been repurposed by a customer but is still flagged as deleted in the Moodle database so it's not safe to just remove anything flagged as deleted.

**Comment by james-cnz** [comment] 2019-03-07 01:37
Hi @dwinn,
Thanks for this, it clarifies things for me a lot.
Regarding deleting parts via the assignment settings, I'm not sure if I understand, but if you mean the page course/modedit.php, the parts flagged for deletion don't show on this page (for me, at least).  I guess this page respects the deletion flag, but shouldn't be doing so?
Regarding not automatically deleting parts flagged for deletion, this makes sense to me, but it would be helpful to be able to locate these so they can be fixed manually.  I've converted hundreds of Turnitin v1 assignments to v2 recently, and I expect there'll be probably be several with this issue, which will cause confusion with submission and marking when they are used again.
Thanks,
James

**Comment by james-cnz** [comment] 2019-04-08 02:27
It looks like a fix for the migration is done?:
fix-deleted parts no longer migrated #519
Any idea when this is likely to ship?

I've attempted to add a fix for the consistent handling of existing migrated v1 parts with the deletion flag set:
Ignore parts deletion flag (untested) #521

I think the following query should find these parts, if used via the Moodle plug-in "Ad-hoc database queries" https://moodle.org/plugins/report_customsql

SELECT c.fullname as "Course name", tii2.course as "Course ID", tii2.name as "TII2 Assignment name", tii2p.turnitintooltwoid as "TII2 Assignment ID", tii2p.partname as "Part name", tii2p.deleted as "Part deleted"
FROM prefix_course AS c
RIGHT JOIN prefix_turnitintool AS tii2 ON c.id = tii2.course
RIGHT JOIN prefix_turnitintooltwo_parts AS tii2p ON tii2.id = tii2p.turnitintooltwoid
WHERE tii2p.deleted != 0

**Comment by dwinn** [comment] 2019-04-09 09:57
Hi @james-cnz,

Thank you for the pull request. It looks ok but I can't merge yet until we test it. I'll see if we can get it into the release.

I think you are correct that some parts of the code respect the deleted flag but some don't. In V2 a part should never be flagged as deleted because the part is removed from the database when deleted, so this never caused a problem until we built the migration tool and carried across deleted flags.

I can't give dates for the release but we are aiming to release before the end of this month if all goes well.

**Comment by dwinn** [comment] 2019-04-10 15:03
I've merged your pull request and tested it, so we can put this into the next release.

**Comment by dwinn** [comment] 2019-05-01 15:01
Hi @james-cnz,

This has now been fixed and released in the latest version - v2019050101.

**Closed by dwinn** 2019-05-01 15:01 UTC
