### ISSUE TITLE
Problem with Migration tool

### ISSUE THREAD

**Issue by mkpelletier** [turnitin/moodle-mod_turnitintooltwo#412] opened 2018-02-05 09:17 UTC
Hello All,
The supplied migration tool to take users with old courses using v1 of the moodle direct plugin is terribly unreliable.  The tool will convert your assignments and preserve the assignment links, however, it completely stuffs up some marks in the gradebook, particularly where there may have been a manually overridden value.  Such things might happen, if for example the student submitted not via Turnitin due to extenuating circumstances.  In this case, the manually recorded mark might be overwritten by a nil value coming from Turnitin.

I have found other instances where the mark is not synchronised at all or is just wrong, but I cannot tell what caused these inconsistencies.

I would love to remove the v1 module, but until a reliable migration tool comes out, I am stuck.

**Comment by jmcgettrick** [comment] 2018-02-05 14:57
Hi @mkpelletier - do you have any more information about the marks that are wrong? 
Are they completely wrong, e.g. should be 50 but is 80? 
Are they large assignments as grades on large assignments are synced when the cron runs? 
Or were they overridden in Moodle's grade center?

**Comment by mkpelletier** [comment] 2018-02-05 16:17
Yes, marks were completely wrong. Most were overridden, but not all. I did
not look closely enough to determine a common factor for these other
assignments.

Sent from my phone
pardon brevity and typos

**Comment by jmcgettrick** [comment] 2018-02-06 09:51
Ok, @mkpelletier we'll get the overridden grades issue fixed. We'll need more information for grades that are wrong.

**Comment by danmarsden** [comment] 2018-02-06 20:49
@mkpelletier you need to make sure you provided specific examples of the issues - grade overrides is something that would be easy to miss - hopefully it's something Turnitin can extract and re-apply to the migrated plugin. You mention "I have found other instances where the mark is not synchronised at all or is just wrong" - can you provide screenshots/configuration/ more information for the turnitin team to help them track that down?

**Comment by mkpelletier** [comment] 2018-02-09 08:29
Hi Dan,
Yes, I am aware of the need for detail when tracking down these kinds of problems.  However, due to the potential disaster that might be awaiting anyone who uses this function, I thought it prudent to report it.  I haven't had the time to track down all the details, but I will post them when I have a chance to do so.

**Comment by danmarsden** [comment] 2018-02-11 05:15
should be enough detail for them to track down the grade override issue - but the other inconsistencies you mention will probably need screenshots etc. AFAIK Turnitin staff don't actually run any live Moodle sites so rely on us to report enough information to help them diagnose.

**Comment by mkpelletier** [comment] 2018-02-23 09:36
Herewith an update on the incorrect migrations:  I have an assignment where the marks recorded are exactly half of what they ought to be.  These were not manually overridden assignments and I can see no offset or other issue in the gradebook that would account for this.

The one problem I _do_ see is that the turnitin module in the converted assignment (v2) is reporting a duplicate assignment with another course.  I am not sure how this can be, since both courses have unique id's in the Turnitin website (i.e Moodle 7810689 and Moodle 8606033).  Somehow the two assignments became conflated when the migration assistant converted these courses to Turnitin_MoodleDirectV2.

Another problem relates to students whose grade do not transfer at all.  That is, the grades are completely blank, though they are present in the original v1 module.  These students are reported in the v1 module as (non moodle user- probably due to an out of sync email address?).  In any case, when the v1 module is converted, these grades are not transferred across.

I hope this helps track down the problems, guys.  John, perhaps you would like to contact me directly for more specifics if necessary.

Thanks again for all the effort!

**Comment by dwinn** [comment] 2018-02-26 15:58
Hi @mkpelletier,

We are changing the workflow a little to solve gradbook issues. Instead of leaving the V1 assignment following a migration we're adding a cleanup process to remove it automatically. This avoids both the V1 and V2 grades being in the gradebook. This deletion will only be performed if the V1 and V2 grades in the gradebook are an exact match. As part of this, grades for the gradebook entry will now be taken from the Moodle grade API rather than the plugin DB tables - this accounts for overridden grades.

Regarding the V2 assignment being flagged as a duplicate from another course - I am not sure how this could occur. The migration tool makes no calls to Turnitin, it simply copies data from the `mdl_turnitintool` database tables to the `mdl_turnitintooltwo` tables. Does the original V1 assignment have a duplicate entry on another course as well? IE was this newer course from a restore process?

For the non-Moodle user - when I create a non-Moodle user they don't appear in the gradebook because they aren't enrolled on the Moodle course. However in my test the grade does copy across to the V2 inbox - this is on both the branch with the new functionality and on master. So maybe there's something we're missing here.

If you could give us further information on the new issues you are reporting or how to reproduce them that would be great because we really want to iron out any issues like this.

**Comment by dwinn** [comment] 2018-02-27 15:15
Hi @mkpelletier,

Would you be able to contact Turnitin support? We will be able to assist you further through the private channels.

**Comment by mkpelletier** [comment] 2018-02-28 07:15
Hi dwinn,
Honestly, I do not have great luck with Turnitin support.  I find I am better able to resolve these problems by contributing to bug reports interacting with the developers on github.

**Comment by jmcgettrick** [comment] 2018-03-19 09:04
Hi @mkpelletier - this has been fixed by https://github.com/turnitin/moodle-mod_turnitintooltwo/releases/tag/v2018031201.

Thanks for raising the issue.

**Closed by jmcgettrick** 2018-03-19 09:04 UTC

**Comment by mkpelletier** [comment] 2018-03-19 09:25
Awesome, John.  You guys rock!
