### ISSUE TITLE
failing to load migration window

### ISSUE THREAD

**Issue by danmarsden** [turnitin/moodle-mod_turnitintooltwo#513] opened 2019-02-14 22:35 UTC
We have a 3.5 site that has a number of old turnitintool plugins that need to be migrated, but the dialog that displays the "migrate" doesn't come up properly - sometimes you catch a flash of the message but then it redirects to the normal view.php page.

seeing this error in the browser console:
TypeError: $.colorbox is not a function[Learn More]
turnitintooltwo_migration_tool-2018102601.js:44:9
displayMigrationModal
https://moodle/theme/jquery.php/mod_turnitintooltwo/turnitintooltwo_migration_tool-2018102601.js:44:9
success
https://moodle/theme/jquery.php/mod_turnitintooltwo/turnitintooltwo_migration_tool-2018102601.js:17:17
i
https://moodle/lib/javascript.php/1550107255/lib/jquery/jquery-3.2.1.min.js:1:28012
fireWith
https://moodle/lib/javascript.php/1550107255/lib/jquery/jquery-3.2.1.min.js:1:28783
A
https://moodle/lib/javascript.php/1550107255/lib/jquery/jquery-3.2.1.min.js:1:78124
c/<
https://moodle/lib/javascript.php/1550107255/lib/jquery/jquery-3.2.1.min.js:1:80414
BSSO Telemetry: {"nonce":"AQABAAEAAACEfexXxjamQb3OeGQ4GugvsxurXPQNy9rQW1yzT22B4kSJbk5GzM4vj8Eh6pikGu

I ended up forcing jquery and colorbox to load in the site header for all pages to see if that helped, but it didn't seem to make any difference.

Is there a reason we can't just have a button on the turnitintool/view.php page that triggers the migration?

thanks,

**Comment by danmarsden** [comment] 2019-02-14 23:00
I've seen anecdotal reports that turning cachejs off on a site seems to fix it.. will do some more testing on this next week.

**Comment by dwinn** [comment] 2019-02-15 10:25
Hi @danmarsden,

Thank you for the report. This is something we are aware of and are currently working on a fix. I'm unsure what the cause is because most of the time it does work, and if it doesn't work first time then a hard refresh of the browser works to get it. We've decided we're going to migrate away from colorbox for this modal and use a Moodle modal instead.

Regarding a button - we had considered that but decided a modal on page load would be a better workflow.

**Comment by danmarsden** [comment] 2019-02-17 20:45
Thanks @dwinn - if you can get it working more reliably then a modal sounds good - it still heavily relies on JS though... so if you can't quite get this working reliably it might be useful to have a standard button to trigger it (or even the ability to manually call a specific url rather than needing to do it all via the ajax/js scripts.

**Comment by dwinn** [comment] 2019-05-01 15:02
Hi @james-cnz,

This has now been fixed and released in the latest version - v2019050101.

We decided to use a Moodle modal for this instead of Colorbox so it should be reliable now in all cases.

**Closed by dwinn** 2019-05-01 15:02 UTC
