### ISSUE TITLE
Error on Moodle Import

### ISSUE THREAD

**Issue by sharpchi** [turnitin/moodle-mod_turnitintooltwo#181] opened 2016-07-08 13:27 UTC
Starting this year we are creating new versions of Moodle courses for each academic year and getting the lecturers to run the Moodle Import process (Course administration -> Import) to bring over content from the previous year.

When they've selected the Moodle course they wish to import from, and then click on "Jump to final step", we are sometimes getting the following error message:
```
turnitintooltwo/There was an error trying to create the assignment in Turnitin

Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: date_start - start date can not be more than 1 year in the past. | Code: 0

More information about this error

Debug info: 
Error code: There was an error trying to create the assignment in Turnitin<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: date_start - start date can not be more than 1 year in the past. 
| Code: 0
$a contents: There was an error trying to create the assignment in Turnitin<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: date_start - start date can not be more than 1 year in the past. 
| Code: 0
Stack trace:
line 488 of /lib/setuplib.php: moodle_exception thrown
line 683 of /mod/turnitintooltwo/lib.php: call to print_error()
line 149 of /mod/turnitintooltwo/turnitintooltwo_comms.class.php: call to turnitintooltwo_print_error()
line 842 of /mod/turnitintooltwo/turnitintooltwo_assignment.class.php: call to turnitintooltwo_comms::handle_exceptions()
line 1385 of /mod/turnitintooltwo/turnitintooltwo_assignment.class.php: call to turnitintooltwo_assignment::create_tii_assignment()
line 125 of /mod/turnitintooltwo/backup/moodle2/restore_turnitintooltwo_activity_task.class.php: call to turnitintooltwo_assignment->edit_moodle_assignment()
line 111 of /backup/util/plan/restore_task.class.php: call to restore_turnitintooltwo_activity_task->after_restore()
line 193 of /backup/util/plan/restore_plan.class.php: call to restore_task->execute_after_restore()
line 121 of /backup/moodle2/restore_final_task.class.php: call to restore_plan->execute_after_restore()
line 821 of /backup/moodle2/restore_stepslib.php: call to restore_final_task->launch_execute_after_restore()
line 34 of /backup/util/plan/restore_execution_step.class.php: call to restore_execute_after_restore->define_execution()
line 181 of /backup/util/plan/base_task.class.php: call to restore_execution_step->execute()
line 177 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
line 167 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 333 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 163 of /backup/import.php: call to restore_controller->execute_plan()
```

This seems to indicate that the source course had a TII2 activity with a start date of more than a year from this moment.

I've run a few tests with old Moodle courses, but this doesn't seem to be consistently producing this error, so I don't know if there's another factor involved in this.

The error doesn't stop the Import process from running, entirely. In fact it seems to import in the TII2 activity, but when you click on it you get the following message:
![tii2error](https://cloud.githubusercontent.com/assets/3774280/16687937/6c089bbe-4513-11e6-9d1d-4de41973b1fe.png)

I looked into this a little bit, and though there's an entry in the course_module table, there _isn't_ an entry in the turnitintooltwo table:
```
select cm.id as cmid,
	c.fullname,
	c.idnumber,
	m.name as modulename,
	tii2.name as tii2name,
	tii2.id as tii2id,
	cm.*
from mdl_course_modules as cm 
JOIN mdl_course as c on c.id=cm.course
JOIN mdl_modules as m on m.id=cm.module
LEFT JOIN mdl_turnitintooltwo as tii2 ON cm.instance = tii2.id
WHERE m.name = 'turnitintooltwo' AND tii2.id IS null;
```
produces:
![tii2_record](https://cloud.githubusercontent.com/assets/3774280/16688182/b8c497d6-4514-11e6-8521-0d2140ee51c2.png)

even though course_module.instance has been set.

It looks to me as though the restore function aborts, but doesn't clean up properly. Since this ends up with a broken link, I would say this is a bug to be fixed.

As far as we are concerned, we are happy if TII2 activities are not imported, but there's no way of automatically stopping that, currently.

I am aware that instead of clicking "Jump to final step" the lecturer could click on "Next" and deselect the TII activities, but _you_ try getting lecturers to jump through those hoops! It's not going to happen.

**Comment by barry-matthias** [comment] 2016-08-30 12:04
Afternoon

I work for blackboard and we can confirm this issue occurs using version 2016011105 of the assignment module, the error which gets generated is as per below

Debug info:
Error code: There was an error trying to create the assignment in Turnitin<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: date_start - start date can not be more than 1 year in the past.
| Code: 0
$a contents: There was an error trying to create the assignment in Turnitin<br/><br/>Fault Code: invaliddata | File: [dirroot]/mod/turnitintooltwo/sdk/assignmentsoap.class.php | Line: 33 | Message: date_start - start date can not be more than 1 year in the past.
| Code: 0
Stack trace

This is being caused by the public function createAssignment( $assignment ) function as the code cant tell if it is being called by the moodle restore or import library below is the entire call stack for this error which should show the parent functions
line 488 of /lib/setuplib.php: moodle_exception thrown
line 683 of /mod/turnitintooltwo/lib.php: call to print_error()
line 149 of /mod/turnitintooltwo/turnitintooltwo_comms.class.php: call to turnitintooltwo_print_error()
line 842 of /mod/turnitintooltwo/turnitintooltwo_assignment.class.php: call to turnitintooltwo_comms::handle_exceptions()
line 1385 of /mod/turnitintooltwo/turnitintooltwo_assignment.class.php: call to turnitintooltwo_assignment::create_tii_assignment()
line 125 of /mod/turnitintooltwo/backup/moodle2/restore_turnitintooltwo_activity_task.class.php: call to turnitintooltwo_assignment->edit_moodle_assignment()
line 111 of /backup/util/plan/restore_task.class.php: call to restore_turnitintooltwo_activity_task->after_restore()
line 193 of /backup/util/plan/restore_plan.class.php: call to restore_task->execute_after_restore()
line 121 of /backup/moodle2/restore_final_task.class.php: call to restore_plan->execute_after_restore()
line 717 of /backup/moodle2/restore_stepslib.php: call to restore_final_task->launch_execute_after_restore()
line 34 of /backup/util/plan/restore_execution_step.class.php: call to restore_execute_after_restore->define_execution()
line 190 of /backup/util/plan/base_task.class.php: call to restore_execution_step->execute()
line 177 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
line 167 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 333 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()

**Comment by dwinn** [comment] 2016-08-30 13:10
Hi @sharpchi and @barry-matthias ,

We have fixed this in our current development build so it will go out with the next release of the V2 plugin.

**Comment by sharpchi** [comment] 2016-08-30 13:33
Thanks for letting us know. I'm not entirely sure it is fixed, though. In the `turnitintooltwo_assignment.class.php` file you have this line:

`if (($restore) && ($attribute < strtotime("-1 year"))) {` 

which checks the `$attribute` value. I would expect that value to be a timestamp, but `$attribute` is set just a few lines up to: 

`$attribute = "maxmarks".$i;`

Would you mind checking please?

**Comment by dwinn** [comment] 2016-08-30 15:15
Hi @sharpchi ,

Thanks for pointing that out, after looking at it myself I do indeed see a bug in our fix. We haven't done our full sweep of QA and automations yet for the next release so we hadn't spotted it yet.

We will amend this before the release.

**Comment by sharpchi** [comment] 2016-08-31 08:10
So, I think you need something like this:

```
$attribute = "dtstart".$i;
if (($restore) && ($this->turnitintooltwo->$attribute < strtotime("-1 year"))) {
```

**Comment by dwinn** [comment] 2016-09-01 11:19
Hi @sharpchi ,

Yeah this is the fix I had in mind. From my testing the fix you propose does work as intended. We'll get it through QA as soon as we can as we aim to release soon.

**Comment by jmcgettrick** [comment] 2016-09-14 08:09
Fixed in v2016091401

**Closed by jmcgettrick** 2016-09-14 08:09 UTC
